(() => {
  'use strict';
  const $=id=>document.getElementById(id), core=window.GPACore;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const fresh=()=>({version:1,branch:'CSE',semester:1,terms:{}});
  let state=fresh(), client=null, user=null, busy=false, identityVersion=0;
  const draftKey='iiits-calculator-guest-v1';
  function valid(s){return s && s.version===1 && ['CSE','ECE'].includes(s.branch) && Number.isInteger(s.semester) && s.semester>=1 && s.semester<=8 && s.terms && typeof s.terms==='object' && !Array.isArray(s.terms) && Object.entries(s.terms).every(([key,t])=>/^(CSE|ECE)\|[1-8]$/.test(key)&&t&&typeof t.include==='boolean'&&typeof t.apply==='boolean'&&Array.isArray(t.rows)&&t.rows.length<=100&&t.rows.every(r=>r&&typeof r.id==='string'&&typeof r.name==='string'&&r.name.length<=120&&typeof r.category==='string'&&r.category.length<=80&&Number.isFinite(Number(r.credits))&&Number(r.credits)>0&&Number(r.credits)<=core.creditCap(r.category)&&(r.grade===''||r.grade in core.grades)&&['string','number'].includes(typeof r.attended)&&['string','number'].includes(typeof r.held)&&(r.attendance===undefined||(r.attendance&&['lectures','labs','missedLectures','missedLabs'].every(k=>['string','number'].includes(typeof r.attendance[k]))&&typeof r.attendance.medical==='boolean'))));}
  try{const draft=JSON.parse(localStorage.getItem(draftKey));if(valid(draft)){state=draft;$('remember').checked=true;}}catch{}
  
  function presetFor(r,branch=state.branch,semester=state.semester){return Object.values(window.CURRICULUM[branch]?.[semester]||{}).flat().find(p=>p.code===(r.code||r.id));}
  function restoreRegisteredCredits(){for(const [key,t] of Object.entries(state.terms)){const [branch,semester]=key.split('|');for(const r of t.rows){const preset=presetFor(r,branch,semester);if(preset)r.credits=preset.credits;}}}
  function term(){const k=state.branch+'|'+state.semester;if(!state.terms[k]){const preset=window.CURRICULUM[state.branch][state.semester]||{};state.terms[k]={include:false,apply:false,rows:Object.entries(preset).flatMap(([category,rows])=>rows.map(r=>({...r,id:r.code,category,grade:'',attended:'',held:''})))};}restoreRegisteredCredits();return state.terms[k];}
  function changed(){if(!user&&$('remember').checked){try{localStorage.setItem(draftKey,JSON.stringify(state));$('draftStatus').textContent='Guest draft saved on this device. It is not an account backup.';}catch{$('draftStatus').textContent='Device storage unavailable. Download a report to retain your work.';}}else if(user){$('authStatus').textContent='Unsaved changes. Use “Save to my account” to keep them across devices.';}}
  function hue(node,value){node.dataset.hue=value===null?'neutral':value>6.5?'green':value>=5?'orange':'red';}
  function totals(){const active=core.aggregate(term().rows,term().apply);$('sgpa').textContent=active.gpa===null?'—':active.gpa.toFixed(2);hue($('sgpa').closest('.score'),active.gpa);$('credits').textContent=active.totalCredits;$('earnedCredits').textContent=active.earnedCredits;
    $('summary').textContent=`${active.results.filter(r=>!r.error).length} / ${term().rows.length} subjects graded · ${active.credits} graded credits${active.complete?'':' · partial estimate'}${active.failed?' · '+active.failed+' failed, rewrite required':''}`;
    const values=Object.entries(state.terms).filter(([k,t])=>k.startsWith(state.branch+'|')&&t.include).map(([,t])=>core.aggregate(t.rows,t.apply));const usable=values.filter(v=>v.gpa!==null),blocked=values.some(v=>v.results.some(r=>r.error&&!r.unselected));const cg=usable.length&&!blocked?usable.reduce((n,v)=>n+v.points,0)/values.reduce((n,v)=>n+v.totalCredits,0):null;
    $('cgpa').textContent=cg===null?'—':cg.toFixed(2);hue($('cgpa'),cg);$('cgpaNote').textContent=values.length?`${values.length} included semester(s) · ${values.every(v=>v.complete)?'complete':'provisional · all registered credits included'}`:'Select semesters to include in CGPA.';
    term().rows.forEach((r,i)=>{const v=active.results[i],node=$('outcome-'+i);if(!node)return;node.textContent=term().apply?(v.att.percent===undefined?'':v.att.percent.toFixed(2)+'% · ')+(v.unselected?'':v.error||`${r.grade||'—'} → ${v.grade} (${v.points})${v.failed?' · Rewrite required':''}`):v.failed?'F · Rewrite required':'';node.hidden=!node.textContent;
      const a=$('attendance-result-'+i);if(a){AttendanceUI.renderResult(a,v.att);}
    });
  }
  function renderAttendance(){const t=term();$('attendanceInputs').hidden=!t.apply;if(!t.apply){$('attendanceInputs').innerHTML='';return;}
    t.rows.forEach(r=>AttendanceUI.init(r,state.semester));
    $('attendanceInputs').innerHTML=`<p>Enter missed hours for each subject. One two-hour lab session counts as one attendance unit. Fixed UG1 semester totals are used. This is a full-semester projection assuming no further absences, not attendance measured to date.</p><p class="small">75% or above: no penalty. 65–below 75%: one subject grade down, unless the institute confirms medical exemption. Below 65%: F by default; exceptional relaxation is case-specific, forwarded by the Dean and approved by the Director. Medical/activity leave needs at least 50% physical attendance. This calculator applies standard physical-attendance rules. For an official exemption, switch attendance adjustment off and enter the institute-confirmed subject grade. UG2/UG3 lab details are awaiting confirmation.</p>${t.rows.map((r,i)=>`<section class="attendance-subject"><h3>${esc(r.name)}</h3>${AttendanceUI.fields(r,i)}<p id="attendance-result-${i}" class="outcome"></p></section>`).join('')}`;
  }
  function render(){const t=term();const supported=t.rows.length>0&&t.rows.every(r=>core.plan(r,state.semester));if(!supported)t.apply=false;$('apply').disabled=!supported;$('attendanceAvailability').hidden=!!supported;$('branch').querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',b.dataset.branch===state.branch));$('include').checked=t.include;$('apply').checked=t.apply;$('semesters').innerHTML=Array.from({length:8},(_,i)=>`<button type="button" data-sem="${i+1}" aria-pressed="${state.semester===i+1}">Sem ${i+1}</button>`).join('');
    const groups=[...new Set(t.rows.map(r=>r.category))];$('subjects').innerHTML=groups.map(category=>`<h2 class="category-title">${esc(category).toUpperCase()}</h2><div class="subject-grid">${t.rows.map((r,i)=>r.category!==category?'':`<article class="subject" data-index="${i}"><h3>${esc(r.name)}</h3>${presetFor(r)?`<p class="small"><strong>${r.credits} registered course credits</strong> · fixed</p>`:`<label>Registered course credits (max ${core.creditCap(r.category)})<input type="number" data-field="credits" min="0.5" max="${core.creditCap(r.category)}" step="0.5" value="${esc(r.credits)}"></label>`}<div class="grades" role="group" aria-label="Grade for ${esc(r.name)}">${Object.entries(core.grades).map(([g,p])=>`<button type="button" data-grade="${g}" title="${core.descriptions[g]}" aria-label="${g}, ${core.descriptions[g]}, ${p} points" aria-pressed="${r.grade===g}">${g}</button>`).join('')}</div><p id="outcome-${i}" class="outcome" aria-live="polite" hidden></p></article>`).join('')}</div>`).join('')||'<section class="panel">Add your registered subjects and credits below.</section>';renderAttendance();totals();}
  async function confirmChange(title,message){$('confirmTitle').textContent=title;$('confirmText').textContent=message;const d=$('confirm');d.returnValue='cancel';d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='yes'),{once:true}));}
  $('semesters').onclick=e=>{const b=e.target.closest('[data-sem]');if(b){state.semester=Number(b.dataset.sem);render();changed();}};
  $('branch').onclick=e=>{const b=e.target.closest('[data-branch]');if(b){state.branch=b.dataset.branch;render();changed();}};
  $('include').onchange=()=>{term().include=$('include').checked;totals();changed();};
  $('apply').onchange=()=>{term().apply=$('apply').checked;renderAttendance();totals();changed();};
  $('subjects').onclick=e=>{const b=e.target.closest('[data-grade]');if(!b)return;const row=b.closest('[data-index]'),i=Number(row.dataset.index),wasComplete=term().rows.every(r=>r.grade in core.grades);term().rows[i].grade=term().rows[i].grade===b.dataset.grade?'':b.dataset.grade;row.querySelectorAll('[data-grade]').forEach(g=>g.setAttribute('aria-pressed',g.dataset.grade===term().rows[i].grade));totals();changed();if(!wasComplete&&term().rows.every(r=>r.grade in core.grades)&&core.aggregate(term().rows,term().apply).complete&&matchMedia('(max-width: 950px)').matches){$('sgpa').closest('.score').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});}};
  $('subjects').oninput=e=>{if(e.target.dataset.field!=='credits')return;const r=term().rows[Number(e.target.closest('[data-index]').dataset.index)],max=core.creditCap(r.category);if(presetFor(r))return;if(Number(e.target.value)>max)e.target.value=max;r.credits=e.target.value;totals();changed();};
  $('attendanceInputs').oninput=e=>{const field=e.target.dataset.att;if(!field)return;const r=term().rows[Number(e.target.closest('[data-att-index]').dataset.attIndex)];if(!['missedLectures','missedLabs'].includes(field))return;r.attendance[field]=e.target.value;totals();changed();};
  const addForm=$('add');function capNew(){const c=addForm.elements.credits,max=core.creditCap(addForm.elements.category.value);c.max=max;if(Number(c.value)>max)c.value=max;}
  addForm.elements.category.onchange=capNew;addForm.elements.credits.oninput=capNew;
  addForm.onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),name=f.get('name').trim();if(!name)return;term().rows.push({id:crypto.randomUUID(),name,category:f.get('category'),credits:Number(f.get('credits')),grade:'',attended:'',held:''});e.target.reset();capNew();render();changed();};
  $('reset').onclick=async()=>{const active=term();if(await confirmChange('Clear semester grades?','Subject names, credits, attendance and other semesters will be kept.')){active.rows.forEach(r=>r.grade='');render();changed();}};
  $('remember').onchange=()=>{if($('remember').checked)changed();else{try{localStorage.removeItem(draftKey);}catch{}$('draftStatus').textContent='Device draft disabled. Guest work is temporary.';}};
  $('theme').onclick=()=>{const theme=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=theme;try{localStorage.setItem('iiits-theme',theme);}catch{}};
  $('report').onclick=()=>{const terms=Object.entries(state.terms).filter(([k])=>k.startsWith(state.branch+'|')).sort();const html=`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>IIITS personal grade report</title><style>body{font:16px/1.5 system-ui;margin:32px;color:#222}table{width:100%;border-collapse:collapse}th,td{padding:8px;text-align:left;border-bottom:1px solid #ccc}section{break-inside:avoid;margin-bottom:32px}</style><h1>IIITS personal grade report</h1><p>${esc(state.branch)} · ${new Date().toLocaleDateString()} · CGPA ${esc($('cgpa').textContent)}</p><p>Personal estimate; not issued by the institute. F = 0, credits retained, rewrite required. Use your browser’s Print → Save as PDF for a PDF copy.</p>${terms.map(([k,t])=>{const a=core.aggregate(t.rows,t.apply);return `<section><h2>Semester ${k.split('|')[1]} · SGPA ${a.gpa===null?'Incomplete':a.gpa.toFixed(2)+(a.complete?'':' (partial estimate)')}</h2><p>Registered credits: ${a.totalCredits} · Earned credits: ${a.earnedCredits}. GPA uses registered credits, including F.</p><p>${t.include?'Included in':'Excluded from'} CGPA. Attendance adjustment ${t.apply?'on':'off'}.</p><table><tr><th>Subject</th><th>Credits</th><th>Entered</th><th>Effective</th><th>Attendance / status</th></tr>${t.rows.map((r,i)=>{const v=a.results[i];return `<tr><td>${esc(r.name)}</td><td>${esc(r.credits)}</td><td>${esc(r.grade? r.grade+' — '+core.descriptions[r.grade]:'—')}</td><td>${esc(v.grade||'—')}</td><td>${esc(v.error|| (v.failed?'F: rewrite required. ':'')+v.att.text)} ${v.att.percent===undefined?'':v.att.percent.toFixed(2)+'%'}</td></tr>`}).join('')}</table></section>`}).join('')}<p>75% or above: no penalty. 65–below 75%: one subject grade down, unless the institute confirms medical exemption. Below 65%: F by default; exceptional relaxation is case-specific, forwarded by the Dean and approved by the Director. Medical/activity leave needs at least 50% physical attendance. Standard physical-attendance rules are estimated here; use institute-confirmed final grades without attendance adjustment for approved exemptions. Presets: pyqsbypa.online/calculator.html.</p></html>`;const link=document.createElement('a'),url=URL.createObjectURL(new Blob([html],{type:'text/html'}));link.href=url;link.download='IIITS-grade-report.html';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  function status(message){$('authStatus').textContent=message;}
  async function task(fn){if(busy)return;busy=true;document.querySelectorAll('#account button').forEach(b=>b.disabled=true);try{await fn();}catch(e){status(e.message||'Connection failed. Your open worksheet is unchanged.');}finally{busy=false;document.querySelectorAll('#account button').forEach(b=>b.disabled=false);}}
  function authView(next){const prior=user?.id;user=next;if(prior!==user?.id){identityVersion++;if(prior){state=fresh();render();}}$('login').hidden=!!user;$('signedIn').hidden=!user;$('remember').disabled=!!user;status(user?'Signed in. Load your saved account data, or save this worksheet.':'Signed out. Guest work stays separate from account data.');}
  async function initAuth(){const config=window.IIITS_SUPABASE;if(!config?.url||!config.publishableKey){$('login').hidden=true;status('Account saving is not connected yet. A guest device draft is available below.');return;}
    try{if(!/^https:\/\/[^/]+\.supabase\.co\/?$/.test(config.url))throw Error('Check the Supabase project URL in configuration.');const sdk=await import('https://esm.sh/@supabase/supabase-js@2.57.4');client=sdk.createClient(config.url,config.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}});const {data,error}=await client.auth.getSession();if(error)throw error;authView(data.session?.user||null);client.auth.onAuthStateChange((_event,session)=>{if(user?.id!==session?.user?.id)authView(session?.user||null);});}catch(e){$('login').hidden=true;status('Account connection unavailable: '+e.message);}}
  let codeEmail='';
  $('sendCode').onsubmit=e=>{e.preventDefault();task(async()=>{const email=$('email').value.trim().toLowerCase();if(!/^[^@\s]+@iiits\.in$/.test(email))throw Error('Use your @iiits.in institute email.');const {error}=await client.auth.signInWithOtp({email});if(error)throw error;codeEmail=email;$('verifyCode').hidden=false;status('Code requested. Check your institute inbox, then enter the code below.');});};
  $('verifyCode').onsubmit=e=>{e.preventDefault();task(async()=>{const {error}=await client.auth.verifyOtp({email:codeEmail,token:$('token').value.trim(),type:'email'});if(error)throw error;$('token').value='';$('verifyCode').hidden=true;});};
  $('saveCloud').onclick=()=>task(async()=>{const id=user.id,version=identityVersion,payload=structuredClone(state);if(!valid(payload))throw Error('Correct invalid subject entries before saving.');const {error}=await client.from('calculator_states').upsert({user_id:id,data:payload},{onConflict:'user_id'});if(error)throw error;if(version===identityVersion)status(JSON.stringify(payload)===JSON.stringify(state)?'Saved to your account. You can close the app and load this on your next visit.':'Snapshot saved. Newer edits remain unsaved.');});
  $('loadCloud').onclick=()=>task(async()=>{const id=user.id,version=identityVersion;if(!await confirmChange('Load account data?','This replaces the open worksheet with your last account save. Download a report first if you need to keep these entries.'))return;const {data,error}=await client.from('calculator_states').select('data').eq('user_id',id).maybeSingle();if(error)throw error;if(version!==identityVersion)return;if(!data){status('No account save yet. Your open worksheet is unchanged.');return;}if(!valid(data.data))throw Error('Saved data has an unsupported format. Your worksheet is unchanged.');state=data.data;render();status('Account data loaded.');});
  $('signOut').onclick=()=>task(async()=>{if(!await confirmChange('Sign out?','Unsaved account edits will be cleared from this worksheet. Save them first if needed.'))return;const {error}=await client.auth.signOut({scope:'local'});if(error)throw error;authView(null);});
  render();if($('remember').checked)changed();initAuth();
})();
